"""Chart helper: real-data, code-rendered chart images (16:9 PNG).

Used to render data tables (e.g. VDOT → pace) as image frames for the video
pipeline. Data is rendered programmatically with matplotlib, not generated by AI
[Crystal ref: D-009].
"""

from __future__ import annotations

from typing import Sequence, Tuple

import matplotlib

matplotlib.use("Agg")  # headless rendering, no display required

import matplotlib.pyplot as plt  # noqa: E402


# Chinese fonts available on macOS: try common ones; matplotlib falls back gracefully.
_CN_FONTS = ["PingFang SC", "STHeiti", "Heiti TC", "Heiti SC", "SimHei", "WenQuanYi Micro Hei"]


def _setup_rcparams() -> None:
    """Configure matplotlib for clean 16:9 chart with Chinese support."""
    matplotlib.rcParams["font.sans-serif"] = list(_CN_FONTS)
    matplotlib.rcParams["font.family"] = "sans-serif"
    matplotlib.rcParams["axes.unicode_minus"] = False
    # 16:9 at 1920x1080 base; scale font sizes up accordingly.
    matplotlib.rcParams["font.size"] = 28
    matplotlib.rcParams["axes.titlesize"] = 36
    matplotlib.rcParams["axes.labelsize"] = 28


def render_pace_table(
    title: str,
    rows: Sequence[Tuple[str, str]],
    out_path: str,
    size: Tuple[int, int] = (1920, 1080),
) -> str:
    """Render a 16:9 chart PNG containing a pace/data table.

    Args:
        title: Chart title (Chinese supported via PingFang SC).
        rows: Sequence of (label, value) pairs to display in the table body.
        out_path: Destination .png file path. Parent directory must exist.
        size: (width, height) in pixels. Defaults to 1920x1080 (16:9 1080p).

    Returns:
        The out_path on success.

    Notes:
        Data is rendered programmatically from the supplied rows. No AI / no
        random generation. Table is centered, with clear headers and rows.
    """
    _setup_rcparams()

    width_in = size[0] / 100.0
    height_in = size[1] / 100.0

    fig, ax = plt.subplots(figsize=(width_in, height_in), dpi=100)
    ax.axis("off")  # hide the Cartesian frame; we only want the table

    fig.patch.set_facecolor("#FAFAFA")
    ax.set_facecolor("#FAFAFA")

    # Build a table with a header row + N data rows.
    table_data = [["配速区间", "对应时间"]] + [list(r) for r in rows]

    tbl = ax.table(
        cellText=table_data,
        colWidths=[0.45, 0.45],
        loc="center",
        cellLoc="center",
    )
    tbl.auto_set_font_size(False)
    tbl.set_fontsize(28)
    tbl.scale(1, 2.2)

    # Style the header row differently from the body.
    for col in range(2):
        cell = tbl[(0, col)]
        cell.set_facecolor("#2C3E50")
        cell.set_text_props(color="white", weight="bold", fontsize=32)
        cell.set_edgecolor("#1A252F")

    # Alternate row striping for readability.
    for row_idx in range(1, len(table_data)):
        face = "#FFFFFF" if row_idx % 2 == 1 else "#ECF0F1"
        for col in range(2):
            cell = tbl[(row_idx, col)]
            cell.set_facecolor(face)
            cell.set_edgecolor("#BDC3C7")
            cell.set_text_props(fontsize=28)

    # Title above the table.
    ax.set_title(title, fontsize=40, weight="bold", pad=24, color="#2C3E50")

    plt.tight_layout(pad=0.5)
    # Fixed-size output: no bbox_inches="tight" (that would crop to content and
    # change the aspect ratio from the requested 16:9). Save at the figure's
    # full canvas size so the resulting PNG is exactly 1920x1080 at dpi=100.
    fig.savefig(out_path, dpi=100, facecolor=fig.get_facecolor())
    plt.close(fig)

    return out_path
